services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: docker
      PG_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 6611:5432
  api:
    image: golang:latest
    command: "./main 8080"
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app