-- TODO create indexes for main search fields
CREATE TABLE IF NOT EXISTS users (
  id SERIAL UNIQUE,
  login TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workers (
  id SERIAL UNIQUE,
  id_user INT UNIQUE NOT NULL REFERENCES users(id),
  uuid TEXT UNIQUE NOT NULL,
  fullname TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  avg_ratings DECIMAL NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
  id SERIAL UNIQUE,
  id_user INT UNIQUE NOT NULL REFERENCES users(id),
  uuid TEXT UNIQUE NOT NULL,
  fullname TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  avg_ratings DECIMAL NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports_workers (
  id SERIAL UNIQUE,
  id_reported_worker INT NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  tags TEXT ARRAY NOT NULL,
  rating DECIMAL NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS reports_customers (
  id SERIAL UNIQUE,
  id_reported_customer INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  tags TEXT ARRAY NOT NULL,
  rating DECIMAL NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS phones (
  id SERIAL UNIQUE,
  id_worker INT NULL REFERENCES workers(id) ON DELETE CASCADE,
  id_customer INT NULL REFERENCES customers(id) ON DELETE CASCADE,
  phone_number TEXT NOT NULL,
  area_code TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS emails (
  id SERIAL UNIQUE,
  id_worker INT NULL REFERENCES workers(id) ON DELETE CASCADE,
  id_customer INT NULL REFERENCES customers(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL UNIQUE,
  id_worker INT NULL REFERENCES workers(id) ON DELETE CASCADE,
  id_customer INT NULL REFERENCES customers(id) ON DELETE CASCADE,
  address TEXT NOT NULL,
  address_number TEXT NOT NULL,
  city TEXT NOT NULL,
  uf TEXT NOT NULL,
  country TEXT NOT NULL,
  main BOOLEAN DEFAULT FALSE,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_services (
  id SERIAL UNIQUE,
  id_worker INT NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  qtdAvailable DECIMAL DEFAULT NULL,
  service BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL UNIQUE,
  id_product_service INT REFERENCES product_services(id) ON DELETE SET NULL,
  id_customer INT REFERENCES customers(id) ON DELETE SET NULL,
  requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scheduled_to TIMESTAMP DEFAULT NULL,
  deployed_at TIMESTAMP DEFAULT NULL,
  description TEXT NOT NULL,
  id_worker_addr INT DEFAULT NULL REFERENCES addresses(id) ON DELETE SET NULL,
  id_customer_addr INT DEFAULT NULL REFERENCES addresses(id) ON DELETE SET NULL,
  online BOOLEAN DEFAULT TRUE,
  quantity DECIMAL NOT NULL DEFAULT 1,
  quantity_by_time DECIMAL NOT NULL DEFAULT 1,
  total_price DECIMAL NOT NULL,
  customer_rating DECIMAL DEFAULT NULL,
  customer_feedback TEXT DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cart_uuid TEXT NOT NULL
);

CREATE INDEX cart ON orders (cart_uuid);
CREATE INDEX sp_name ON product_services (name);

CREATE INDEX c_uuid ON customers (uuid);
CREATE INDEX w_uuid ON workers (uuid);
